# Generated by Django 4.1 on 2022-12-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
