# Generated by Django 4.1 on 2022-10-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='likes',
            new_name='like',
        ),
    ]
