# Generated by Django 4.1 on 2022-12-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_idname_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='idName',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
