# Generated by Django 4.1 on 2022-10-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_blog_comment_comment_parentblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentBlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
    ]
