# Generated by Django 4.1 on 2022-10-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_comment_parentblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='message',
        ),
    ]
