# Generated by Django 4.1 on 2022-12-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_category_name_category_idname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='idName',
            new_name='name',
        ),
    ]
