# Generated by Django 4.1 on 2022-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_message_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blogImage/default.png', null=True, upload_to='blogImage/'),
        ),
    ]
