# Generated by Django 4.1 on 2022-10-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobileNo',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userBio',
            field=models.TextField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='userImage'),
        ),
    ]
