# Generated by Django 4.1 on 2022-10-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userImage',
            field=models.ImageField(blank=True, default='userImage/default.png', null=True, upload_to='userImage/'),
        ),
    ]
